/* eslint-disable no-console */
import React from 'react';
import { Box } from '@mui/material';
import SectionBuilder from '../library/components/organisms_new/SectionBuilder';

const pageData = [
  {
    elType: 'container',
    settings: {
      position: 'relative',
      flex_direction: 'column',
      flex_justify_content: 'center',
      flex_align_items: 'center',
      background_color: '#FFFFFF',
      border: '1px solid pink',
      padding: {
        top: '20',
        right: '20',
        bottom: '20',
        left: '20',
      },
    },
    elements: [
      {
        elType: 'widget',
        widgetType: 'heading',
        settings: {
          title: 'Take Action Now',
          title_color: '#000000',
          typography_font_size: { size: '32' },
          align: 'center',
        },
      },
      {
        elType: 'widget',
        widgetType: 'text-editor',
        settings: {
          editor: "Let's create your next big project together.",
          text_color: '#333333',
          typography_font_size: { size: '18' },
          align: 'center',
        },
      },
      {
        elType: 'widget',
        widgetType: 'button',
        settings: {
          text: 'Get Started',
          background_color: '#1976D2',
          button_text_color: '#FFFFFF',
          border_radius: { top: '8' },
          text_padding: {
            top: '10',
            right: '20',
            bottom: '10',
            left: '20',
          },
          link: { url: 'https://www.conventionalcommits.org/en/v1.0.0/' },
        },
      },
      {
        elType: 'widget',
        settings: {
          image_size: 'full',
          image: { url: 'https://picsum.photos/id/56/3000/2000', id: 50411, source: 'url' },
          height: 9,
          width: { unit: '%', size: 800, sizes: [] },
          _z_index: 0,
          _title: 'Frame',
        },
        isInner: false,
        elements: [],
        id: '31b0fb1f',
        widgetType: 'image',
      },
      {
        elType: 'widget',
        settings: {
          ending_number: '22',
          typography_number_color: '#0D0D0D',
          typography_number_font_size: { unit: 'px', size: 48, sizes: [] },
          typography_number_font_weight: '500',
          suffix: '+',
          title: 'Years of Experience',
          typography_title_color: '#808080',
          typography_title_font_size: { unit: 'px', size: 20, sizes: [] },
          typography_title_font_weight: '400',
          typography_title_text_transform: 'none',
          typography_title_text_decoration: 'none',
          typography_title_line_height: { unit: 'em', size: 1.5, sizes: [] },
          typography_title_letter_spacing: { unit: 'em', size: 0, sizes: [] },
          starting_number: 0,
          _z_index: 0,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: '32a99f5e',
        widgetType: 'counter',
      },
    ],
  },
  {
    elType: 'container',
    settings: {
      content_width: 'full',
      width: { unit: '%', size: 79.43, sizes: [] },
      flex_direction: 'row',
      flex_justify_content: 'space-between',
      flex_align_items: 'center',
      padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
      z_index: 1,
      uich_custom_css_field: 'selector {\n  max-width: 100%;\n}\n',
      _title: 'Countdown',
    },
    isInner: false,
    elements: [
      {
        elType: 'widget',
        settings: {
          ending_number: '22',
          number_color: '#0D0D0D',
          number: {
            suffix: '+',
            typography: 'custom',
            font_family: 'Plus Jakarta Sans',
            font_style: 'normal',
            font_size: { unit: 'px', size: 48, sizes: [] },
            font_weight: '500',
            text_transform: 'none',
            text_decoration: 'none',
            line_height: { unit: 'em', size: 1.25, sizes: [] },
            letter_spacing: { unit: 'em', size: -0.02, sizes: [] },
          },
          title: {
            text: 'Years of Experience',
            color: '#808080',
            typography: 'custom',
            font_family: 'Plus Jakarta Sans',
            font_style: 'normal',
            font_size: { unit: 'px', size: 20, sizes: [] },
            font_weight: '400',
            text_transform: 'none',
            text_decoration: 'none',
            line_height: { unit: 'em', size: 1.5, sizes: [] },
            letter_spacing: { unit: 'em', size: 0, sizes: [] },
          },
          thousand_separator: '',
          starting_number: 0,
          _padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
          _element_width: 'initial',
          _element_custom_width: { unit: '%', size: 22.32, sizes: [] },
          _element_width_mobile: 'initial',
          _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
          _z_index: 0,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: '32a99f5e',
        widgetType: 'countero',
      },
      {
        elType: 'widget',
        settings: {
          ending_number: '700',
          number_color: '#0D0D0D',
          typography_number_typography: 'custom',
          typography_number_font_family: 'Plus Jakarta Sans',
          typography_number_font_style: 'normal',
          typography_number_font_size: { unit: 'px', size: 48, sizes: [] },
          typography_number_font_weight: '500',
          typography_number_text_transform: 'none',
          typography_number_text_decoration: 'none',
          typography_number_line_height: { unit: 'em', size: 1.25, sizes: [] },
          typography_number_letter_spacing: { unit: 'em', size: -0.02, sizes: [] },
          suffix: '+',
          title: 'Total Courses',
          title_color: '#808080',
          typography_title_typography: 'custom',
          typography_title_font_family: 'Plus Jakarta Sans',
          typography_title_font_style: 'normal',
          typography_title_font_size: { unit: 'px', size: 20, sizes: [] },
          typography_title_font_weight: '400',
          typography_title_text_transform: 'none',
          typography_title_text_decoration: 'none',
          typography_title_line_height: { unit: 'em', size: 1.5, sizes: [] },
          typography_title_letter_spacing: { unit: 'em', size: 0, sizes: [] },
          thousand_separator: '',
          starting_number: 0,
          _padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
          _element_width: 'initial',
          _element_custom_width: { unit: '%', size: 20.54, sizes: [] },
          _element_width_mobile: 'initial',
          _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
          _z_index: 2,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: '23ee3ae1',
        widgetType: 'counter',
      },
      {
        elType: 'widget',
        settings: {
          ending_number: '1',
          typography_number_color: 'red',
          typography_number_typography: 'custom',
          typography_number_font_family: 'Plus Jakarta Sans',
          typography_number_font_style: 'normal',
          typography_number_font_size: { unit: 'px', size: 48, sizes: [] },
          typography_number_font_weight: '500',
          typography_number_text_transform: 'none',
          typography_number_text_decoration: 'none',
          typography_number_line_height: { unit: 'em', size: 1.25, sizes: [] },
          typography_number_letter_spacing: { unit: 'em', size: -0.02, sizes: [] },
          suffix: 'K+',
          title: 'Satisfied Customer',
          typography_title_color: 'blue',
          typography_title_typography: 'custom',
          typography_title_font_family: 'Plus Jakarta Sans',
          typography_title_font_style: 'normal',
          typography_title_font_size: { unit: 'px', size: 20, sizes: [] },
          typography_title_font_weight: '400',
          typography_title_text_transform: 'none',
          typography_title_text_decoration: 'none',
          typography_title_line_height: { unit: 'em', size: 1.5, sizes: [] },
          typography_title_letter_spacing: { unit: 'em', size: 0, sizes: [] },
          thousand_separator: '',
          starting_number: 0,
          _padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
          _element_width: 'initial',
          _element_custom_width: { unit: '%', size: 22.32, sizes: [] },
          _element_width_mobile: 'initial',
          _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
          _z_index: 4,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: 'da88ee71',
        widgetType: 'counter',
      },
      {
        elType: 'widget',
        settings: {
          ending_number: '100',
          number_color: '#0D0D0D',
          typography_number_typography: 'custom',
          typography_number_font_family: 'Plus Jakarta Sans',
          typography_number_font_style: 'normal',
          typography_number_font_size: { unit: 'px', size: 48, sizes: [] },
          typography_number_font_weight: '500',
          typography_number_text_transform: 'none',
          typography_number_text_decoration: 'none',
          typography_number_line_height: { unit: 'em', size: 1.25, sizes: [] },
          typography_number_letter_spacing: { unit: 'em', size: -0.02, sizes: [] },
          suffix: '+',
          title: 'Certificates & Awards',
          title_color: '#808080',
          typography_title_typography: 'custom',
          typography_title_font_family: 'Plus Jakarta Sans',
          typography_title_font_style: 'normal',
          typography_title_font_size: { unit: 'px', size: 20, sizes: [] },
          typography_title_font_weight: '400',
          typography_title_text_transform: 'none',
          typography_title_text_decoration: 'none',
          typography_title_line_height: { unit: 'em', size: 1.5, sizes: [] },
          typography_title_letter_spacing: { unit: 'em', size: 0, sizes: [] },
          thousand_separator: '',
          starting_number: 0,
          _padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
          _element_width: 'initial',
          _element_custom_width: { unit: '%', size: 20.54, sizes: [] },
          _element_width_mobile: 'initial',
          _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
          _z_index: 6,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: '1318b00b',
        widgetType: 'counter',
      },
    ],
    id: '5cf4ed40',
  },
];

const Page = () => {
  return (
    <Box>
      {pageData.map((sectionData, index) => (
        <Box componente="SectionBuilderWrapper" key={index} sx={{ width: '100%', p: '20px', border: '5px solid black' }}>
          <SectionBuilder data={sectionData} />
        </Box>
      ))}
    </Box>
  );
};

export default Page;
