const pageData = [
  {
    elType: 'container',
    settings: {
      position: 'relative',
      flex_direction: 'column',
      flex_justify_content: 'center',
      flex_align_items: 'center',
      background_color: '#FFFFFF',
      border: '1px solid pink',
      padding: {
        top: '20',
        right: '20',
        bottom: '20',
        left: '20',
      },
    },
    elements: [
      {
        elType: 'widget',
        widgetType: 'heading',
        settings: {
          title: 'Take Action Now',
          title_color: '#000000',
          typography_font_size: { size: '32' },
          align: 'center',
        },
      },
      {
        elType: 'widget',
        widgetType: 'text-editor',
        settings: {
          editor: "Let's create your next big project together.",
          text_color: '#333333',
          typography_font_size: { size: '18' },
          align: 'center',
        },
      },
      {
        elType: 'widget',
        widgetType: 'button',
        settings: {
          text: 'Get Started',
          background_color: '#1976D2',
          button_text_color: '#FFFFFF',
          border_radius: { top: '8' },
          text_padding: {
            top: '10',
            right: '20',
            bottom: '10',
            left: '20',
          },
          link: { url: 'https://www.conventionalcommits.org/en/v1.0.0/' },
        },
      },
      {
        elType: 'widget',
        settings: {
          image_size: 'full',
          image: { url: 'https://picsum.photos/id/56/3000/2000', id: 50411, source: 'url' },
          height: 9,
          width: { unit: '%', size: 800, sizes: [] },
          _z_index: 0,
          _title: 'Frame',
        },
        isInner: false,
        elements: [],
        id: '31b0fb1f',
        widgetType: 'image',
      },
      {
        elType: 'widget',
        settings: {
          ending_number: '22',
          typography_number_color: '#0D0D0D',
          typography_number_font_size: { unit: 'px', size: 48, sizes: [] },
          typography_number_font_weight: '500',
          suffix: '+',
          title: 'Years of Experience',
          typography_title_color: '#808080',
          typography_title_font_size: { unit: 'px', size: 20, sizes: [] },
          typography_title_font_weight: '400',
          typography_title_text_transform: 'none',
          typography_title_text_decoration: 'none',
          typography_title_line_height: { unit: 'em', size: 1.5, sizes: [] },
          typography_title_letter_spacing: { unit: 'em', size: 0, sizes: [] },
          starting_number: 0,
          _z_index: 0,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: '32a99f5e',
        widgetType: 'counter',
      },
    ],
  },
  {
    elType: 'container',
    settings: {
      content_width: 'full',
      width: { unit: '%', size: 79.43, sizes: [] },
      flex_direction: 'row',
      flex_justify_content: 'space-between',
      flex_align_items: 'center',
      padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
      z_index: 1,
      uich_custom_css_field: 'selector {\n  max-width: 100%;\n}\n',
      _title: 'Countdown',
    },
    isInner: false,
    elements: [
      {
        elType: 'widget',
        settings: {
          ending_number: '700',
          number_color: '#0D0D0D',
          typography_number_typography: 'custom',
          typography_number_font_family: 'Plus Jakarta Sans',
          typography_number_font_style: 'normal',
          typography_number_font_size: { unit: 'px', size: 48, sizes: [] },
          typography_number_font_weight: '500',
          typography_number_text_transform: 'none',
          typography_number_text_decoration: 'none',
          typography_number_line_height: { unit: 'em', size: 1.25, sizes: [] },
          typography_number_letter_spacing: { unit: 'em', size: -0.02, sizes: [] },
          suffix: '+',
          title: 'Total Courses',
          title_color: 'yellow',
          typography_title_typography: 'custom',
          typography_title_font_family: 'Plus Jakarta Sans',
          typography_title_font_style: 'normal',
          typography_title_font_size: { unit: 'px', size: 20, sizes: [] },
          typography_title_font_weight: '400',
          typography_title_text_transform: 'none',
          typography_title_text_decoration: 'none',
          typography_title_line_height: { unit: 'em', size: 1.5, sizes: [] },
          typography_title_letter_spacing: { unit: 'em', size: 0, sizes: [] },
          thousand_separator: '',
          starting_number: 0,
          _padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
          _element_width: 'initial',
          _element_custom_width: { unit: '%', size: 20.54, sizes: [] },
          _element_width_mobile: 'initial',
          _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
          _z_index: 2,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: '23ee3ae1',
        widgetType: 'counter',
      },
      {
        elType: 'widget',
        settings: {
          ending_number: '1',
          number_color: 'red',
          typography_number_typography: 'custom',
          typography_number_font_family: 'Plus Jakarta Sans',
          typography_number_font_style: 'normal',
          typography_number_font_size: { unit: 'px', size: 48, sizes: [] },
          typography_number_font_weight: '500',
          typography_number_text_transform: 'none',
          typography_number_text_decoration: 'none',
          typography_number_line_height: { unit: 'em', size: 1.25, sizes: [] },
          typography_number_letter_spacing: { unit: 'em', size: -0.02, sizes: [] },
          suffix: 'K+',
          title: 'Satisfied Customer',
          title_color: 'purple',
          typography_title_typography: 'custom',
          typography_title_font_family: 'Plus Jakarta Sans',
          typography_title_font_style: 'normal',
          typography_title_font_size: { unit: 'px', size: 20, sizes: [] },
          typography_title_font_weight: '400',
          typography_title_text_transform: 'none',
          typography_title_text_decoration: 'none',
          typography_title_line_height: { unit: 'em', size: 1.5, sizes: [] },
          typography_title_letter_spacing: { unit: 'em', size: 0, sizes: [] },
          thousand_separator: '',
          starting_number: 0,
          _padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
          _element_width: 'initial',
          _element_custom_width: { unit: '%', size: 22.32, sizes: [] },
          _element_width_mobile: 'initial',
          _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
          _z_index: 4,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: 'da88ee71',
        widgetType: 'counter',
      },
      {
        elType: 'widget',
        settings: {
          ending_number: '100',
          number_color: 'red',
          typography_number_typography: 'custom',
          typography_number_font_family: 'Plus Jakarta Sans',
          typography_number_font_style: 'normal',
          typography_number_font_size: { unit: 'px', size: 48, sizes: [] },
          typography_number_font_weight: '500',
          typography_number_text_transform: 'none',
          typography_number_text_decoration: 'none',
          typography_number_line_height: { unit: 'em', size: 1.25, sizes: [] },
          typography_number_letter_spacing: { unit: 'em', size: -0.02, sizes: [] },
          suffix: '+',
          title: 'Certificates & Awards',
          title_color: 'green',
          typography_title_typography: 'custom',
          typography_title_font_family: 'Plus Jakarta Sans',
          typography_title_font_style: 'normal',
          typography_title_font_size: { unit: 'px', size: 20, sizes: [] },
          typography_title_font_weight: '400',
          typography_title_text_transform: 'none',
          typography_title_text_decoration: 'none',
          typography_title_line_height: { unit: 'em', size: 1.5, sizes: [] },
          typography_title_letter_spacing: { unit: 'em', size: 0, sizes: [] },
          thousand_separator: '',
          starting_number: 0,
          _padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' },
          _element_width: 'initial',
          _element_custom_width: { unit: '%', size: 20.54, sizes: [] },
          _element_width_mobile: 'initial',
          _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
          _z_index: 6,
          _title: 'Text',
        },
        isInner: false,
        elements: [],
        id: '1318b00b',
        widgetType: 'counter',
      },
    ],
    id: '5cf4ed40',
  },
  {
    elType: 'container',
    settings: { content_width: 'full', flex_direction: 'column', flex_justify_content: 'center', flex_align_items: 'center', padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' }, flex_gap_tablet: { column: '15', row: '15', isLinked: false, unit: 'px', size: 15 }, z_index: 4, position: 'absolute', _offset_x: { unit: 'px', size: 0, sizes: [] }, _offset_y: { unit: 'px', size: 2998, sizes: [] }, background_background: 'classic', background_color: '#FFFFFF', width_mobile: { unit: '%', size: 100, sizes: [] }, width_tablet: { unit: '%', size: 100, sizes: [] }, uich_custom_css_field: 'selector {\n  max-width: 100%;\n}\n', padding_mobile: { unit: 'px', isLinked: false, top: '0', right: '20', bottom: '0', left: '20' }, padding_tablet: { unit: 'px', isLinked: false, top: '0', right: '25', bottom: '0', left: '25' }, _title: 'Why Choose Us' },
    isInner: false,
    elements: [
      {
        elType: 'container',
        settings: { content_width: 'full', flex_direction: 'column', flex_justify_content: 'flex-start', flex_align_items: 'center', padding: { unit: 'px', isLinked: false, top: '100', right: '15', bottom: '100', left: '15' }, padding_tablet: { unit: 'px', isLinked: false, top: '58', right: '15', bottom: '58', left: '15' }, padding_mobile: { unit: 'px', isLinked: false, top: '23.2', right: '15', bottom: '23.2', left: '15' }, flex_gap: { column: '50', row: '50', isLinked: false, unit: 'px', size: 50 }, flex_gap_tablet: { column: '15', row: '15', isLinked: false, unit: 'px', size: 15 }, z_index: 0, background_background: 'classic', background_color: '#FFFFFF', width_mobile: { unit: '%', size: 100, sizes: [] }, width_tablet: { unit: '%', size: 100, sizes: [] }, uich_custom_css_field: 'selector {\n  max-width: 100%;\n}\n', _title: 'Frame' },
        isInner: false,
        elements: [
          {
            elType: 'container',
            settings: { content_width: 'full', width: { unit: '%', size: 79.43, sizes: [] }, flex_direction: 'row', flex_justify_content: 'flex-start', flex_align_items: 'flex-start', padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' }, flex_gap: { column: '119', row: '119', isLinked: false, unit: 'px', size: 119 }, flex_gap_tablet: { column: '15', row: '15', isLinked: false, unit: 'px', size: 15 }, z_index: 0, width_mobile: { unit: 'px', size: 1120, sizes: [] }, width_tablet: { unit: 'px', size: 1120, sizes: [] }, flex_wrap_mobile: 'wrap', flex_wrap_tablet: 'wrap', uich_custom_css_field: 'selector {\n  max-width: 100%;\n}\n', _title: 'Frame' },
            isInner: false,
            elements: [
              {
                elType: 'container',
                settings: { content_width: 'full', width: { unit: '%', size: 48.57, sizes: [] }, flex_direction: 'column', flex_justify_content: 'flex-start', flex_align_items: 'flex-start', padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' }, flex_gap: { column: '4', row: '4', isLinked: false, unit: 'px', size: 4 }, z_index: 0, width_mobile: { unit: 'px', size: 544, sizes: [] }, width_tablet: { unit: 'px', size: 544, sizes: [] }, uich_custom_css_field: 'selector {\n  max-width: 100%;\n  min-width: 240px;\n}\n', _title: 'Frame' },
                isInner: false,
                elements: [
                  {
                    elType: 'container',
                    settings: { content_width: 'full', width: { unit: '%', size: 23.71, sizes: [] }, flex_direction: 'row', flex_justify_content: 'center', flex_align_items: 'center', padding: { unit: 'px', isLinked: false, top: '6', right: '12', bottom: '6', left: '12' }, padding_tablet: { unit: 'px', isLinked: false, top: '6', right: '12', bottom: '6', left: '12' }, padding_mobile: { unit: 'px', isLinked: false, top: '6', right: '12', bottom: '6', left: '12' }, flex_gap: { column: '10', row: '10', isLinked: false, unit: 'px', size: 10 }, z_index: 0, border_border: 'solid', border_width: { unit: 'px', top: '1', right: '1', bottom: '1', left: '1', isLinked: false }, border_color: '#3328BF', border_radius: { unit: 'px', top: '50', right: '50', bottom: '50', left: '50', isLinked: false }, width_mobile: { unit: 'px', size: 129, sizes: [] }, width_tablet: { unit: 'px', size: 129, sizes: [] }, uich_custom_css_field: 'selector {\n  max-width: 100%;\n}\n', _title: 'Frame' },
                    isInner: false,
                    elements: [{ elType: 'widget', settings: { header_size: 'div', typography_typography: 'custom', title: 'Why Choose Us', title_color: '#3328BF', typography_font_family: 'Plus Jakarta Sans', typography_font_style: 'normal', typography_font_size: { unit: 'px', size: 14, sizes: [] }, typography_font_size_tablet: { unit: 'px', size: 12.04, sizes: [] }, typography_font_size_mobile: { unit: 'px', size: 14, sizes: [] }, typography_font_weight: '500', align: 'center', typography_text_transform: 'none', typography_text_decoration: 'none', typography_line_height: { unit: 'em', size: 1.43, sizes: [] }, typography_line_height_tablet: { unit: 'em', size: 1.43, sizes: [] }, typography_line_height_mobile: { unit: 'em', size: 1.29, sizes: [] }, typography_letter_spacing: { unit: 'em', size: 0, sizes: [] }, _element_width: 'initial', _element_custom_width: { unit: 'custom', size: 'max-content', sizes: [] }, _z_index: 0, _element_custom_width_tablet: { unit: 'custom', size: 'auto', sizes: [] }, _title: 'Why Choose Us' }, isInner: false, elements: [], id: '354f0d79', widgetType: 'heading' }],
                    id: '451d05a7',
                  },
                  { elType: 'widget', settings: { header_size: 'div', typography_typography: 'custom', title: 'Creative and Unique Solutions', title_color: '#0D0D0D', typography_font_family: 'Plus Jakarta Sans', typography_font_style: 'normal', typography_font_size: { unit: 'px', size: 48, sizes: [] }, typography_font_size_tablet: { unit: 'px', size: 26.69, sizes: [] }, typography_font_size_mobile: { unit: 'px', size: 24.48, sizes: [] }, typography_font_weight: '500', typography_text_transform: 'none', typography_text_decoration: 'none', typography_line_height: { unit: 'em', size: 1.25, sizes: [] }, typography_line_height_tablet: { unit: 'em', size: 1.25, sizes: [] }, typography_line_height_mobile: { unit: 'em', size: 1.2, sizes: [] }, typography_letter_spacing: { unit: 'em', size: -0.02, sizes: [] }, _element_width: 'initial', _element_custom_width: { unit: '%', size: 100, sizes: [] }, _z_index: 1, _element_custom_width_tablet: { unit: 'px', size: 544, sizes: [] }, _title: 'Creative and Unique Solutions' }, isInner: false, elements: [], id: '20f651fe', widgetType: 'heading' },
                ],
                id: 'adec4f78',
              },
              {
                elType: 'container',
                settings: { content_width: 'full', width: { unit: '%', size: 40.8, sizes: [] }, flex_direction: 'column', flex_justify_content: 'flex-start', flex_align_items: 'flex-start', padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' }, flex_gap: { column: '24', row: '24', isLinked: false, unit: 'px', size: 24 }, flex_gap_tablet: { column: '15', row: '15', isLinked: false, unit: 'px', size: 15 }, z_index: 1, width_mobile: { unit: 'px', size: 457, sizes: [] }, width_tablet: { unit: 'px', size: 457, sizes: [] }, uich_custom_css_field: 'selector {\n  max-width: 100%;\n  min-width: 240px;\n}\n', _title: 'Frame' },
                isInner: false,
                elements: [
                  { elType: 'widget', settings: { typography_typography: 'custom', typography_font_family: 'Plus Jakarta Sans', typography_font_style: 'normal', typography_font_size: { unit: 'px', size: 16, sizes: [] }, typography_font_size_tablet: { unit: 'px', size: 15.04, sizes: [] }, typography_font_size_mobile: { unit: 'px', size: 14.08, sizes: [] }, typography_font_weight: '400', typography_text_transform: 'none', typography_text_decoration: 'none', typography_line_height: { unit: 'em', size: 1.5, sizes: [] }, typography_line_height_tablet: { unit: 'em', size: 1.42, sizes: [] }, typography_line_height_mobile: { unit: 'em', size: 1.32, sizes: [] }, typography_letter_spacing: { unit: 'em', size: 0, sizes: [] }, editor: 'We adhere to the highest standards of quality in all our products and services. From design and development to manufacturing and customer support, we maintain rigorous quality control measures to ensure consistency.', text_color: '#808080', align: 'left', _element_width: 'initial', _element_custom_width: { unit: '%', size: 100, sizes: [] }, _z_index: 0, _element_custom_width_tablet: { unit: 'px', size: 457, sizes: [] }, _title: 'We adhere to the highest standards of quality in all our products and services. From design and development to manufacturing and customer support, we maintain rigorous quality control measures to ensure consistency.' }, isInner: false, elements: [], id: '8eae7cea', widgetType: 'text-editor' },
                  {
                    elType: 'widget',
                    settings: {
                      text: 'Learn More',
                      align: 'justify',
                      typography_typography: 'custom',
                      typography_font_family: 'Plus Jakarta Sans',
                      typography_font_style: 'normal',
                      typography_font_size: { unit: 'px', size: 16, sizes: [] },
                      typography_font_size_tablet: { unit: 'px', size: 15.04, sizes: [] },
                      typography_font_size_mobile: { unit: 'px', size: 14.08, sizes: [] },
                      typography_font_weight: '600',
                      typography_text_transform: 'none',
                      typography_text_decoration: 'none',
                      typography_line_height: { unit: 'em', size: 1.5, sizes: [] },
                      typography_line_height_tablet: { unit: 'em', size: 1.42, sizes: [] },
                      typography_line_height_mobile: { unit: 'em', size: 1.32, sizes: [] },
                      typography_letter_spacing: { unit: 'em', size: 0, sizes: [] },
                      button_text_color: '#FCFCFC',
                      selected_icon: { value: { url: 'https://api.uichemy.com/res/755492063360703515/3944b9274ee639385c3b4dce065edffe.svg', id: 53596 }, library: 'svg' },
                      border_border: 'solid',
                      border_width: { unit: 'px', top: '1', right: '1', bottom: '1', left: '1', isLinked: false },
                      border_color: '#3328BF',
                      border_radius: { unit: 'px', top: '8', right: '8', bottom: '8', left: '8', isLinked: false },
                      background_background: 'classic',
                      background_color: 'red',
                      _z_index: 1,
                      text_padding: { unit: 'px', isLinked: false, top: '10', right: '16', bottom: '10', left: '16' },
                      button_box_shadow_box_shadow_type: 'yes',
                      button_box_shadow_box_shadow: { horizontal: 0, vertical: 1, blur: 2, spread: 0, color: 'rgba(16, 24, 40, 0.05)' },
                      text_padding_tablet: { unit: 'px', isLinked: false, top: '10', right: '12.8', bottom: '10', left: '12.8' },
                      text_padding_mobile: { unit: 'px', isLinked: false, top: '9.5', right: '12.8', bottom: '9.5', left: '12.8' },
                      link: { url: '#', is_external: '', nofollow: '', custom_attributes: '' },
                      icon_align: 'right',
                      icon_indent: { unit: 'px', size: 6, sizes: [] },
                      _title: 'Buttons/Button',
                    },
                    isInner: false,
                    elements: [],
                    id: '6442fd21',
                    widgetType: 'button',
                  },
                ],
                id: '3abcd5dc',
              },
            ],
            id: '305ea6e6',
          },
          {
            elType: 'container',
            settings: { content_width: 'full', width: { unit: '%', size: 79.43, sizes: [] }, flex_direction: 'row', flex_justify_content: 'center', flex_align_items: 'center', padding: { unit: 'px', isLinked: false, top: '0', right: '0', bottom: '0', left: '0' }, flex_gap: { column: '32', row: '32', isLinked: false, unit: 'px', size: 32 }, flex_gap_tablet: { column: '15', row: '15', isLinked: false, unit: 'px', size: 15 }, z_index: 1, width_mobile: { unit: 'px', size: 1120, sizes: [] }, width_tablet: { unit: 'px', size: 1120, sizes: [] }, flex_wrap_mobile: 'wrap', flex_wrap_tablet: 'wrap', uich_custom_css_field: 'selector {\n  max-width: 100%;\n}\n', _title: 'Frame' },
            isInner: false,
            elements: [
              {
                elType: 'widget',
                settings: {
                  title_text: 'Workout',
                  description_text: 'Our workouts are tailored to accommodate all fitness levels.',
                  _padding: { unit: 'px', isLinked: false, top: '40', right: '20', bottom: '40', left: '20' },
                  _padding_tablet: { unit: 'px', isLinked: false, top: '25.36', right: '15.78', bottom: '25.36', left: '15.78' },
                  _padding_mobile: { unit: 'px', isLinked: false, top: '18.04', right: '12.64', bottom: '18.04', left: '12.64' },
                  _element_width: 'initial',
                  _element_custom_width: { unit: '%', size: 31.43, sizes: [] },
                  _element_width_mobile: 'initial',
                  _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
                  _border_border: 'solid',
                  _border_width: { unit: 'px', top: '1', right: '1', bottom: '1', left: '1', isLinked: false },
                  _border_color: '#D6D6D6',
                  _border_radius: { unit: 'px', top: '30', right: '30', bottom: '30', left: '30', isLinked: false },
                  _z_index: 0,
                  selected_icon: { value: { url: 'https://api.uichemy.com/res/755492063360703515/c2d3602f9ecafc591a44ca439f5ea717.svg', id: 66407 }, library: 'svg' },
                  primary_color: 'red',
                  icon_size: { unit: 'px', size: 100, sizes: [] },
                  title_color: '#0D0D0D',
                  title_typography_typography: 'custom',
                  title_typography_font_family: 'Plus Jakarta Sans',
                  title_typography_font_style: 'normal',
                  title_typography_font_size: { unit: 'px', size: 30, sizes: [] },
                  title_typography_font_size_tablet: { unit: 'px', size: 21.27, sizes: [] },
                  title_typography_font_size_mobile: { unit: 'px', size: 18.9, sizes: [] },
                  title_typography_font_weight: '500',
                  title_typography_text_transform: 'none',
                  title_typography_text_decoration: 'none',
                  title_typography_line_height: { unit: 'em', size: 1.27, sizes: [] },
                  title_typography_line_height_tablet: { unit: 'em', size: 1.27, sizes: [] },
                  title_typography_line_height_mobile: { unit: 'em', size: 1.2, sizes: [] },
                  title_typography_letter_spacing: { unit: 'em', size: 0, sizes: [] },
                  text_align: 'center',
                  description_color: '#808080',
                  description_typography_typography: 'custom',
                  description_typography_font_family: 'Plus Jakarta Sans',
                  description_typography_font_style: 'normal',
                  description_typography_font_size: { unit: 'px', size: 16, sizes: [] },
                  description_typography_font_size_tablet: { unit: 'px', size: 15.04, sizes: [] },
                  description_typography_font_size_mobile: { unit: 'px', size: 14.08, sizes: [] },
                  description_typography_font_weight: '400',
                  description_typography_text_transform: 'none',
                  description_typography_text_decoration: 'none',
                  description_typography_line_height: { unit: 'em', size: 1.5, sizes: [] },
                  description_typography_line_height_tablet: { unit: 'em', size: 1.42, sizes: [] },
                  description_typography_line_height_mobile: { unit: 'em', size: 1.32, sizes: [] },
                  description_typography_letter_spacing: { unit: 'em', size: 0, sizes: [] },
                  rotate: { unit: 'deg', size: 0, sizes: [] },
                  title_size: 'h3',
                  icon_space: { unit: 'px', size: 12, sizes: [] },
                  title_bottom_space: { unit: 'px', size: 12, sizes: [] },
                  _title: 'Frame',
                },
                isInner: false,
                elements: [],
                id: 'df92994a',
                widgetType: 'icon-box',
              },
              {
                elType: 'widget',
                settings: {
                  title_text: 'Nutrition',
                  description_text: 'Our mission is to provide you with valuable resources.',
                  _padding: { unit: 'px', isLinked: false, top: '40', right: '20', bottom: '40', left: '20' },
                  _padding_tablet: { unit: 'px', isLinked: false, top: '25.36', right: '15.78', bottom: '25.36', left: '15.78' },
                  _padding_mobile: { unit: 'px', isLinked: false, top: '18.04', right: '12.64', bottom: '18.04', left: '12.64' },
                  _element_width: 'initial',
                  _element_custom_width: { unit: '%', size: 31.43, sizes: [] },
                  _element_width_mobile: 'initial',
                  _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
                  _border_border: 'solid',
                  _border_width: { unit: 'px', top: '1', right: '1', bottom: '1', left: '1', isLinked: false },
                  _border_color: '#D6D6D6',
                  _border_radius: { unit: 'px', top: '30', right: '30', bottom: '30', left: '30', isLinked: false },
                  _z_index: 1,
                  selected_icon: { value: { url: 'https://api.uichemy.com/res/755492063360703515/b4a575070da020d4600b14d4944aa258.svg', id: 95388 }, library: 'svg' },
                  primary_color: '#3328BF',
                  icon_size: { unit: 'px', size: 100, sizes: [] },
                  title_color: '#0D0D0D',
                  title_typography_typography: 'custom',
                  title_typography_font_family: 'Plus Jakarta Sans',
                  title_typography_font_style: 'normal',
                  title_typography_font_size: { unit: 'px', size: 30, sizes: [] },
                  title_typography_font_size_tablet: { unit: 'px', size: 21.27, sizes: [] },
                  title_typography_font_size_mobile: { unit: 'px', size: 18.9, sizes: [] },
                  title_typography_font_weight: '500',
                  title_typography_text_transform: 'none',
                  title_typography_text_decoration: 'none',
                  title_typography_line_height: { unit: 'em', size: 1.27, sizes: [] },
                  title_typography_line_height_tablet: { unit: 'em', size: 1.27, sizes: [] },
                  title_typography_line_height_mobile: { unit: 'em', size: 1.2, sizes: [] },
                  title_typography_letter_spacing: { unit: 'em', size: 0, sizes: [] },
                  text_align: 'center',
                  description_color: '#808080',
                  description_typography_typography: 'custom',
                  description_typography_font_family: 'Plus Jakarta Sans',
                  description_typography_font_style: 'normal',
                  description_typography_font_size: { unit: 'px', size: 16, sizes: [] },
                  description_typography_font_size_tablet: { unit: 'px', size: 15.04, sizes: [] },
                  description_typography_font_size_mobile: { unit: 'px', size: 14.08, sizes: [] },
                  description_typography_font_weight: '400',
                  description_typography_text_transform: 'none',
                  description_typography_text_decoration: 'none',
                  description_typography_line_height: { unit: 'em', size: 1.5, sizes: [] },
                  description_typography_line_height_tablet: { unit: 'em', size: 1.42, sizes: [] },
                  description_typography_line_height_mobile: { unit: 'em', size: 1.32, sizes: [] },
                  description_typography_letter_spacing: { unit: 'em', size: 0, sizes: [] },
                  rotate: { unit: 'deg', size: 0, sizes: [] },
                  title_size: 'h3',
                  icon_space: { unit: 'px', size: 12, sizes: [] },
                  title_bottom_space: { unit: 'px', size: 12, sizes: [] },
                  _title: 'Frame',
                },
                isInner: false,
                elements: [],
                id: '5e11bc15',
                widgetType: 'icon-box',
              },
              {
                elType: 'widget',
                settings: {
                  title_text: 'Progression',
                  description_text: 'Our focus on progression is what sets us apart and ensures that.',
                  _padding: { unit: 'px', isLinked: false, top: '40', right: '20', bottom: '40', left: '20' },
                  _padding_tablet: { unit: 'px', isLinked: false, top: '25.36', right: '15.78', bottom: '25.36', left: '15.78' },
                  _padding_mobile: { unit: 'px', isLinked: false, top: '18.04', right: '12.64', bottom: '18.04', left: '12.64' },
                  _element_width: 'initial',
                  _element_custom_width: { unit: '%', size: 31.43, sizes: [] },
                  _element_width_mobile: 'initial',
                  _element_custom_width_mobile: { unit: '%', size: 100, sizes: [] },
                  _border_border: 'solid',
                  _border_width: { unit: 'px', top: '1', right: '1', bottom: '1', left: '1', isLinked: false },
                  _border_color: '#D6D6D6',
                  _border_radius: { unit: 'px', top: '30', right: '30', bottom: '30', left: '30', isLinked: false },
                  _z_index: 2,
                  selected_icon: { value: { url: 'https://api.uichemy.com/res/755492063360703515/5f24376ca30c2cde27fb64865ce67363.svg', id: 65940 }, library: 'svg' },
                  primary_color: '#3328BF',
                  icon_size: { unit: 'px', size: 100, sizes: [] },
                  title_color: '#0D0D0D',
                  title_typography_typography: 'custom',
                  title_typography_font_family: 'Plus Jakarta Sans',
                  title_typography_font_style: 'normal',
                  title_typography_font_size: { unit: 'px', size: 30, sizes: [] },
                  title_typography_font_size_tablet: { unit: 'px', size: 21.27, sizes: [] },
                  title_typography_font_size_mobile: { unit: 'px', size: 18.9, sizes: [] },
                  title_typography_font_weight: '500',
                  title_typography_text_transform: 'none',
                  title_typography_text_decoration: 'none',
                  title_typography_line_height: { unit: 'em', size: 1.27, sizes: [] },
                  title_typography_line_height_tablet: { unit: 'em', size: 1.27, sizes: [] },
                  title_typography_line_height_mobile: { unit: 'em', size: 1.2, sizes: [] },
                  title_typography_letter_spacing: { unit: 'em', size: 0, sizes: [] },
                  text_align: 'center',
                  description_color: '#808080',
                  description_typography_typography: 'custom',
                  description_typography_font_family: 'Plus Jakarta Sans',
                  description_typography_font_style: 'normal',
                  description_typography_font_size: { unit: 'px', size: 16, sizes: [] },
                  description_typography_font_size_tablet: { unit: 'px', size: 15.04, sizes: [] },
                  description_typography_font_size_mobile: { unit: 'px', size: 14.08, sizes: [] },
                  description_typography_font_weight: '400',
                  description_typography_text_transform: 'none',
                  description_typography_text_decoration: 'none',
                  description_typography_line_height: { unit: 'em', size: 1.5, sizes: [] },
                  description_typography_line_height_tablet: { unit: 'em', size: 1.42, sizes: [] },
                  description_typography_line_height_mobile: { unit: 'em', size: 1.32, sizes: [] },
                  description_typography_letter_spacing: { unit: 'em', size: 0, sizes: [] },
                  rotate: { unit: 'deg', size: 0, sizes: [] },
                  title_size: 'h3',
                  icon_space: { unit: 'px', size: 12, sizes: [] },
                  title_bottom_space: { unit: 'px', size: 12, sizes: [] },
                  _title: 'Frame',
                },
                isInner: false,
                elements: [],
                id: 'c5d0c84c',
                widgetType: 'icon-box',
              },
            ],
            id: '7c2ca052',
          },
        ],
        id: '87d39921',
      },
    ],
    id: 'bda5fb12',
  },
];

export default pageData;
